### PR TITLE
feat(elections): allow admins to always nominate and set results

### PR DESCRIPTION
**Pull request by bnjns**
Allows admins to always add/remove nominations and set the results outside the nomination/voting windows.

Resolves https://github.com/backstage-technical-services/hub/issues/139

### CODE REVIEW

**Comment by ACascarino** [comment]
@bnjns merging without review? tut tut :p

(this is a joke)

**Comment by bnjns** [comment]
> @bnjns merging without review? tut tut :p
> 
> (this is a joke)

Are you telling me other people actually wait for people to review their PRs?!! :scream: :wink:

**Comment by ACascarino** [comment]
at work Github's set up that we _have to_ lol, doesn't let us merge without it

**Comment by bnjns** [comment]
Benefits of being a repo admin or org owner - you can bypass the branch protection

**Pull request merged**
